// Log In
export const WEBSITE_LOG_IN_UPDATE_EMAIL = 'WEBSITE_LOG_IN_UPDATE_EMAIL';
export const WEBSITE_LOG_IN_UPDATE_PASSWORD = 'WEBSITE_LOG_IN_UPDATE_PASSWORD';
export const WEBSITE_LOG_IN_COMPLETE_SUCCESS = 'WEBSITE_LOG_IN_COMPLETE_SUCCESS';

// Patient Lookup
export const PATIENT_LOOKUP_INITIALIZE = 'PATIENT_LOOKUP_INITIALIZE';
export const PATIENT_LOOKUP_UPDATE_EMAIL = 'PATIENT_LOOKUP_UPDATE_EMAIL';
export const PATIENT_LOOKUP_UPDATE_MOBILE = 'PATIENT_LOOKUP_UPDATE_MOBILE';

// Patient Creation
export const PATIENT_CREATION_UPDATE_FIRST_NAME = 'PATIENT_CREATION_UPDATE_FIRST_NAME';
export const PATIENT_CREATION_UPDATE_LAST_NAME = 'PATIENT_CREATION_UPDATE_LAST_NAME';
export const PATIENT_CREATION_UPDATE_EMAIL = 'PATIENT_CREATION_UPDATE_EMAIL';
export const PATIENT_CREATION_UPDATE_MOBILE = 'PATIENT_CREATION_UPDATE_MOBILE';
